name: 🔢 Hash Check Failed
description: Report SHA256 hash mismatches or checksum validation failures
title: "[Hash]: "
labels: ["bug", "auto-fix"]
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    description: Before reporting, please verify
    options:
    - label: I have verified the error by running `scoop install <app-name>` recently
      required: true
    - label: I have run `scoop update` and still get the hash error
      required: true

- type: input
  attributes:
    label: Package Name and Version
    description: Format as packname@version (use package name, not display name)
    placeholder: e.g. duckstation@20251115 (not DuckStation)
  validations:
    required: true

- type: textarea
  attributes:
    label: Error Message
    description: Copy the exact hash error message from Scoop
    render: console
    placeholder: |
      Hash check failed!
      Expected: abc123...
      Got: def456...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Installation Method
    description: How did you install the package?
    options:
      - Fresh install (`scoop install <app>`)
      - Update (`scoop update <app>`)
      - Update all (`scoop update *`)
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: Any other information
    placeholder: |
      - Windows version: Windows 11 22H2
      - Antivirus software: None
      - Network: Direct connection / VPN / Proxy
  required: false

- type: markdown
  attributes:
    value: |
      **Note:** Hash mismatches are automatically detected and fixed by our system within 1 hour.
      If the error persists after that time, check GitHub Actions logs or file a new issue.

      See [Manifest Error](./manifest-error.yml) template for other manifest-related issues.

