on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

name: Review and Verify

jobs:
  scoop_handler:
    name: Scoop Action Handler
    runs-on: windows-latest
    if: >-
      github.event_name == 'pull_request_target' ||
      (github.event_name == 'issues' && (github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify')))) ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/verify'))
    steps:
      - uses: actions/checkout@v7
      - name: Handler
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

